[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.1"

[[constraint]]
  name = "github.com/openfaas/faas"
  version = "0.18.2"

[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "0.10.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.1"

[prune]
  go-tests = true
  unused-packages = true
